apiVersion: v1
kind: ConfigMap
metadata:
  name: imaptoasm-config
data:
  config.cfg: |-
    [default]
    IMAP_SERVER: {{ .Values.config.imapServer }}
    EMAIL_ACCOUNT: {{ .Values.config.emailAccount }}
    EMAIL_FOLDER: {{ .Values.config.emailFolder }}
    PASSWORD: {{ .Values.config.password }}
    AL_SERVER: {{ .Values.config.alServer }}
    AL_USER: {{ .Values.config.alUser }}
    AL_APIKEY: {{ .Values.config.alApiKey }}
    SLEEP: {{ .Values.config.sleep }}
    CF_CID: {{ .Values.config.cfCid }}
    CF_CSECRET: {{ .Values.config.cfCsecret }}