apiVersion: v1
kind: Secret
metadata:
  name: imaptoasm-config
type: Opaque
data:
    [default]
    IMAP_SERVER: your-imap-server
    EMAIL_ACCOUNT: your-email-account
    EMAIL_FOLDER: your-email-folder
    PASSWORD: your-password
    AL_SERVER: your-al-server
    AL_USER: your-al-user
    AL_APIKEY: your-al-apikey
    SLEEP: "5"
    CF_CID: your-cf-cid
    CF_CSECRET: your-cf-csecret